version : '3'

networks:
  sf_network:
    driver: bridge

services:
  sf:
    build: .
    container_name: project_app
    depends_on:
      - database
    ports:
      - "80:80"
    volumes:
      - ./log:/var/log/apache2
      - ./app:/var/www/html
      - ./vhosts:/etc/apache2/sites-enabled
    networks:
      - sf_network

  database:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: project_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sf_db
      MYSQL_ROOT_PASSWORD: password

    networks:
      - sf_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database
    expose:
      - "3307"
    ports:
      - "3307:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      - sf_network

  mail:
    image: maildev/maildev
    container_name: Maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080
    networks:
      - sf_network

#  www:
#    build: docker
#    container_name: www
#    ports:
#      - "8000:80"
#    volumes:
#      - ./docker/vhosts:/etc/apache2/sites-enabled
#      - ./:/var/www
#    networks:
#      - sf_network